### ISSUE TITLE
Review notes

### ISSUE THREAD

**Issue by chrisvfritz** [Xenimus/project10#1]
Looks mostly very good. I just see one thing I'd like you to update:
- When I'm not signed in and on the Show page, I still see a link to Edit, which should probably be hidden since I can't _really_ edit anything.

**Comment by Xenimus** [comment]
I thought i commented on this last week saying that i updated it, but i must have forgotten to. Its updated now

**Comment by chrisvfritz** [comment]
:+1: Looks good!
